parameters:
#    abcd_test.example.class: Abcd\TestBundle\Example

services:
#    abcd_test.example:
#        class: %abcd_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    hello_service:
        class: Abcd\TestBundle\Services\HelloService